"""Seed the database with 42 known UAE PPP projects."""
from __future__ import annotations
import asyncio
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.db.session import init_db, AsyncSessionLocal
from backend.db.crud import upsert_project

SEED_PROJECTS: list[dict] = [
    # Transport — Dubai
    {
        "name": "Dubai Metro Blue Line",
        "sector": "Transport",
        "emirate": "Dubai",
        "owner": "Roads and Transport Authority (RTA)",
        "contract_value_aed": 30.0,
        "status": "Under Execution",
        "contractors": "Alstom, Acciona, Gülermak",
        "expected_completion_year": 2029,
        "source_url": "https://www.rta.ae/wps/portal/rta/ae/public-transport/metro",
        "source_name": "RTA Dubai",
        "extraction_confidence": 0.95,
        "notes": "14 stations, 30 km extension of metro network",
    },
    {
        "name": "Dubai Metro Red Line Extension to Expo City",
        "sector": "Transport",
        "emirate": "Dubai",
        "owner": "Roads and Transport Authority (RTA)",
        "contract_value_aed": 10.6,
        "status": "Complete",
        "contractors": "Alstom, Acciona",
        "expected_completion_year": 2021,
        "source_url": "https://www.rta.ae",
        "source_name": "RTA Dubai",
        "extraction_confidence": 0.95,
        "notes": "Route 2020 extension for Expo 2020",
    },
    {
        "name": "RTA Bus Rapid Transit (BRT) Network",
        "sector": "Transport",
        "emirate": "Dubai",
        "owner": "Roads and Transport Authority (RTA)",
        "contract_value_aed": 4.5,
        "status": "Planned",
        "contractors": None,
        "expected_completion_year": 2028,
        "source_url": "https://www.rta.ae",
        "source_name": "RTA Dubai",
        "extraction_confidence": 0.85,
        "notes": "Rapid bus network across Dubai emirate",
    },
    {
        "name": "Al Maktoum International Airport Phase 2",
        "sector": "Transport",
        "emirate": "Dubai",
        "owner": "Dubai Airports",
        "contract_value_aed": 128.0,
        "status": "Tendering",
        "contractors": None,
        "expected_completion_year": 2034,
        "source_url": "https://www.dubaiairports.ae",
        "source_name": "Dubai Airports",
        "extraction_confidence": 0.9,
        "notes": "Will become world's largest airport with capacity for 260M passengers",
    },
    {
        "name": "Jebel Ali Port Expansion P4",
        "sector": "Transport",
        "emirate": "Dubai",
        "owner": "DP World",
        "contract_value_aed": 15.0,
        "status": "Under Execution",
        "contractors": "Jan De Nul",
        "expected_completion_year": 2026,
        "source_url": "https://www.dpworld.com",
        "source_name": "DP World",
        "extraction_confidence": 0.9,
        "notes": "Additional container terminal capacity",
    },
    # Transport — Abu Dhabi
    {
        "name": "Etihad Rail Network",
        "sector": "Transport",
        "emirate": "Federal",
        "owner": "Etihad Rail",
        "contract_value_aed": 50.0,
        "status": "Under Execution",
        "contractors": "China Railway Construction Corporation, Alstom",
        "expected_completion_year": 2027,
        "source_url": "https://www.etihadrail.ae",
        "source_name": "Etihad Rail",
        "extraction_confidence": 0.95,
        "notes": "1,200 km national freight and passenger railway network",
    },
    {
        "name": "Abu Dhabi International Airport Midfield Terminal",
        "sector": "Transport",
        "emirate": "Abu Dhabi",
        "owner": "Abu Dhabi Airports",
        "contract_value_aed": 30.0,
        "status": "Complete",
        "contractors": "TAV Construction, Arabtec, CCC",
        "expected_completion_year": 2023,
        "source_url": "https://www.abudhabiairport.ae",
        "source_name": "Abu Dhabi Airports",
        "extraction_confidence": 0.95,
        "notes": "New terminal with 45M passenger capacity",
    },
    {
        "name": "Khalifa Port Expansion Phase 2",
        "sector": "Transport",
        "emirate": "Abu Dhabi",
        "owner": "Abu Dhabi Ports (AD Ports Group)",
        "contract_value_aed": 8.0,
        "status": "Under Execution",
        "contractors": "DEME, Van Oord",
        "expected_completion_year": 2025,
        "source_url": "https://www.adports.ae",
        "source_name": "AD Ports Group",
        "extraction_confidence": 0.9,
        "notes": "Semi-automated container terminal expansion",
    },
    {
        "name": "Fujairah Airport Terminal Expansion",
        "sector": "Transport",
        "emirate": "Fujairah",
        "owner": "Fujairah Airport",
        "contract_value_aed": 1.8,
        "status": "Planned",
        "contractors": None,
        "expected_completion_year": 2027,
        "source_url": "https://www.fujairahairport.ae",
        "source_name": "Fujairah Airport",
        "extraction_confidence": 0.8,
        "notes": "New international terminal building",
    },
    {
        "name": "Ajman Port Development",
        "sector": "Transport",
        "emirate": "Ajman",
        "owner": "Ajman Seaport",
        "contract_value_aed": 2.2,
        "status": "Tendering",
        "contractors": None,
        "expected_completion_year": 2027,
        "source_url": "https://www.ajmanseaport.ae",
        "source_name": "Ajman Seaport",
        "extraction_confidence": 0.8,
        "notes": "Port modernisation and capacity expansion PPP",
    },
    # Energy — Dubai
    {
        "name": "Mohammed bin Rashid Al Maktoum Solar Park Phase 5",
        "sector": "Energy",
        "emirate": "Dubai",
        "owner": "Dubai Electricity and Water Authority (DEWA)",
        "contract_value_aed": 11.4,
        "status": "Under Execution",
        "contractors": "Masdar, EDF Renewables",
        "expected_completion_year": 2026,
        "source_url": "https://www.dewa.gov.ae",
        "source_name": "DEWA",
        "extraction_confidence": 0.95,
        "notes": "900 MW solar PV, IPP model",
    },
    {
        "name": "Hassyan Clean Coal Power Plant",
        "sector": "Energy",
        "emirate": "Dubai",
        "owner": "Dubai Electricity and Water Authority (DEWA)",
        "contract_value_aed": 13.6,
        "status": "Under Execution",
        "contractors": "Harbin Electric, Acwa Power",
        "expected_completion_year": 2023,
        "source_url": "https://www.dewa.gov.ae",
        "source_name": "DEWA",
        "extraction_confidence": 0.9,
        "notes": "2,400 MW clean coal IPP project",
    },
    {
        "name": "DEWA Wind Power Project (Hatta Pumped Storage)",
        "sector": "Energy",
        "emirate": "Dubai",
        "owner": "Dubai Electricity and Water Authority (DEWA)",
        "contract_value_aed": 1.42,
        "status": "Under Execution",
        "contractors": "Andritz Hydro",
        "expected_completion_year": 2024,
        "source_url": "https://www.dewa.gov.ae",
        "source_name": "DEWA",
        "extraction_confidence": 0.9,
        "notes": "250 MW pumped hydro storage facility",
    },
    # Energy — Abu Dhabi
    {
        "name": "Barakah Nuclear Power Plant",
        "sector": "Energy",
        "emirate": "Abu Dhabi",
        "owner": "Emirates Nuclear Energy Corporation (ENEC)",
        "contract_value_aed": 85.0,
        "status": "Under Execution",
        "contractors": "Korea Electric Power Corporation (KEPCO)",
        "expected_completion_year": 2026,
        "source_url": "https://www.enec.gov.ae",
        "source_name": "ENEC",
        "extraction_confidence": 0.95,
        "notes": "4 units, 5,600 MW total capacity — Arab world's first nuclear plant",
    },
    {
        "name": "Al Dhafra Solar PV Project",
        "sector": "Energy",
        "emirate": "Abu Dhabi",
        "owner": "Abu Dhabi Power Corporation (ADPower)",
        "contract_value_aed": 5.5,
        "status": "Under Execution",
        "contractors": "Masdar, EDF, Jinko Power",
        "expected_completion_year": 2023,
        "source_url": "https://www.adpower.ae",
        "source_name": "ADPower",
        "extraction_confidence": 0.95,
        "notes": "2,000 MW — world's largest single-site solar plant",
    },
    {
        "name": "Al Reyadah Carbon Capture Plant",
        "sector": "Energy",
        "emirate": "Abu Dhabi",
        "owner": "Abu Dhabi National Energy Company (TAQA)",
        "contract_value_aed": 2.1,
        "status": "Complete",
        "contractors": "GE, Siemens Energy",
        "expected_completion_year": 2016,
        "source_url": "https://www.alreyadah.ae",
        "source_name": "Al Reyadah",
        "extraction_confidence": 0.9,
        "notes": "World's first industrial carbon capture in steel production",
    },
    {
        "name": "Fujairah F3 Power and Desalination Plant",
        "sector": "Energy",
        "emirate": "Fujairah",
        "owner": "Abu Dhabi Power Corporation",
        "contract_value_aed": 7.5,
        "status": "Under Execution",
        "contractors": "GE Gas Power, Sumitomo",
        "expected_completion_year": 2025,
        "source_url": "https://www.adpower.ae",
        "source_name": "ADPower",
        "extraction_confidence": 0.85,
        "notes": "2,000 MW gas-fired combined cycle + 120 MIGD desalination",
    },
    {
        "name": "Hamriyah Power Plant (Sharjah)",
        "sector": "Energy",
        "emirate": "Sharjah",
        "owner": "Sharjah Electricity, Water and Gas Authority (SEWA)",
        "contract_value_aed": 4.2,
        "status": "Under Execution",
        "contractors": "Siemens Energy",
        "expected_completion_year": 2025,
        "source_url": "https://www.sewa.gov.ae",
        "source_name": "SEWA",
        "extraction_confidence": 0.85,
        "notes": "1,800 MW gas-fired power plant",
    },
    {
        "name": "Ras Al Khaimah Waste-to-Energy Plant",
        "sector": "Environment",
        "emirate": "Ras Al Khaimah",
        "owner": "Bee'ah / Veolia RAK",
        "contract_value_aed": 1.1,
        "status": "Tendering",
        "contractors": None,
        "expected_completion_year": 2027,
        "source_url": "https://www.beeah.ae",
        "source_name": "Bee'ah",
        "extraction_confidence": 0.8,
        "notes": "270,000-tonne capacity waste-to-energy facility PPP",
    },
    # Water
    {
        "name": "Al Taweelah Desalination and Power Plant",
        "sector": "Water",
        "emirate": "Abu Dhabi",
        "owner": "Abu Dhabi Power Corporation",
        "contract_value_aed": 6.8,
        "status": "Complete",
        "contractors": "Acwa Power, Engie",
        "expected_completion_year": 2022,
        "source_url": "https://www.adpower.ae",
        "source_name": "ADPower",
        "extraction_confidence": 0.9,
        "notes": "2,400 MW power + 200 MIGD desalination, IPP/IWPP",
    },
    {
        "name": "Shuwaihat 3 Water Plant (IWPP)",
        "sector": "Water",
        "emirate": "Abu Dhabi",
        "owner": "Abu Dhabi Power Corporation",
        "contract_value_aed": 4.2,
        "status": "Complete",
        "contractors": "Acwa Power, GE",
        "expected_completion_year": 2018,
        "source_url": "https://www.adpower.ae",
        "source_name": "ADPower",
        "extraction_confidence": 0.9,
        "notes": "1,600 MW + 100 MIGD desalination facility",
    },
    {
        "name": "DEWA Reverse Osmosis Desalination Plant (Jebel Ali)",
        "sector": "Water",
        "emirate": "Dubai",
        "owner": "Dubai Electricity and Water Authority (DEWA)",
        "contract_value_aed": 3.6,
        "status": "Under Execution",
        "contractors": "Acciona Agua",
        "expected_completion_year": 2025,
        "source_url": "https://www.dewa.gov.ae",
        "source_name": "DEWA",
        "extraction_confidence": 0.9,
        "notes": "120 MIGD reverse osmosis plant, IPP model",
    },
    {
        "name": "Umm Al Nar Power and Water Station Expansion",
        "sector": "Water",
        "emirate": "Abu Dhabi",
        "owner": "Abu Dhabi Power Corporation",
        "contract_value_aed": 5.0,
        "status": "Tendering",
        "contractors": None,
        "expected_completion_year": 2027,
        "source_url": "https://www.adpower.ae",
        "source_name": "ADPower",
        "extraction_confidence": 0.85,
        "notes": "Additional desalination capacity 80 MIGD",
    },
    {
        "name": "UAE Water Security Strategy Projects",
        "sector": "Water",
        "emirate": "Multiple",
        "owner": "Ministry of Energy and Infrastructure",
        "contract_value_aed": 20.0,
        "status": "Planned",
        "contractors": None,
        "expected_completion_year": 2036,
        "source_url": "https://www.moei.gov.ae",
        "source_name": "MOEI",
        "extraction_confidence": 0.8,
        "notes": "National water security infrastructure programme",
    },
    # Healthcare
    {
        "name": "Abu Dhabi Hospitals PPP Program (Sheikh Shakhbout Medical City)",
        "sector": "Healthcare",
        "emirate": "Abu Dhabi",
        "owner": "Department of Health Abu Dhabi",
        "contract_value_aed": 4.1,
        "status": "Complete",
        "contractors": "Mayo Clinic, Mubadala",
        "expected_completion_year": 2020,
        "source_url": "https://www.ssmc-uae.com",
        "source_name": "SSMC",
        "extraction_confidence": 0.95,
        "notes": "Quaternary care hospital, 741 beds, PPP with Mayo Clinic",
    },
    {
        "name": "Dubai Healthcare City Phase 2",
        "sector": "Healthcare",
        "emirate": "Dubai",
        "owner": "Dubai Healthcare City Authority (DHCA)",
        "contract_value_aed": 5.5,
        "status": "Under Execution",
        "contractors": "Limitless, National Bonds Corporation",
        "expected_completion_year": 2027,
        "source_url": "https://www.dhca.gov.ae",
        "source_name": "DHCA",
        "extraction_confidence": 0.85,
        "notes": "Medical district expansion with specialist hospitals and research facilities",
    },
    {
        "name": "Sharjah University Hospital PPP",
        "sector": "Healthcare",
        "emirate": "Sharjah",
        "owner": "University of Sharjah",
        "contract_value_aed": 1.8,
        "status": "Under Execution",
        "contractors": "G4S Healthcare, Arabtec",
        "expected_completion_year": 2025,
        "source_url": "https://www.sharjah.ac.ae",
        "source_name": "University of Sharjah",
        "extraction_confidence": 0.8,
        "notes": "500-bed teaching hospital PPP",
    },
    {
        "name": "RAK Hospital Expansion PPP",
        "sector": "Healthcare",
        "emirate": "Ras Al Khaimah",
        "owner": "Ras Al Khaimah Medical District",
        "contract_value_aed": 0.9,
        "status": "Tendering",
        "contractors": None,
        "expected_completion_year": 2026,
        "source_url": "https://www.rakmd.ae",
        "source_name": "RAK Medical District",
        "extraction_confidence": 0.75,
        "notes": "Specialist cancer and cardiac care expansion",
    },
    # Education
    {
        "name": "ADEK Schools PPP Program",
        "sector": "Education",
        "emirate": "Abu Dhabi",
        "owner": "Abu Dhabi Department of Education and Knowledge (ADEK)",
        "contract_value_aed": 3.5,
        "status": "Under Execution",
        "contractors": "GEMS Education, Aldar Properties",
        "expected_completion_year": 2025,
        "source_url": "https://www.adek.gov.ae",
        "source_name": "ADEK",
        "extraction_confidence": 0.9,
        "notes": "25 new government schools under PPP model",
    },
    {
        "name": "KHDA Dubai Private Schools PPP",
        "sector": "Education",
        "emirate": "Dubai",
        "owner": "Knowledge and Human Development Authority (KHDA)",
        "contract_value_aed": 2.0,
        "status": "Under Execution",
        "contractors": "GEMS Education, Nord Anglia",
        "expected_completion_year": 2025,
        "source_url": "https://www.khda.gov.ae",
        "source_name": "KHDA",
        "extraction_confidence": 0.85,
        "notes": "Private school development on government land",
    },
    {
        "name": "Khalifa University Campus Expansion",
        "sector": "Education",
        "emirate": "Abu Dhabi",
        "owner": "Khalifa University",
        "contract_value_aed": 1.5,
        "status": "Under Execution",
        "contractors": "Al Futtaim Engineering",
        "expected_completion_year": 2025,
        "source_url": "https://www.ku.ac.ae",
        "source_name": "Khalifa University",
        "extraction_confidence": 0.85,
        "notes": "New STEM research facilities and student housing",
    },
    # Environment
    {
        "name": "Bee'ah Sharjah Integrated Environment Solutions",
        "sector": "Environment",
        "emirate": "Sharjah",
        "owner": "Sharjah City for Humanitarian Services / Bee'ah",
        "contract_value_aed": 2.2,
        "status": "Under Execution",
        "contractors": "Bee'ah",
        "expected_completion_year": 2025,
        "source_url": "https://www.beeah.ae",
        "source_name": "Bee'ah",
        "extraction_confidence": 0.9,
        "notes": "Zero waste to landfill by 2025 programme",
    },
    {
        "name": "Dubai Waste Management City (Warsan)",
        "sector": "Environment",
        "emirate": "Dubai",
        "owner": "Dubai Municipality",
        "contract_value_aed": 4.5,
        "status": "Under Execution",
        "contractors": "Hitachi Zosen Inova, Itochu",
        "expected_completion_year": 2024,
        "source_url": "https://www.dm.gov.ae",
        "source_name": "Dubai Municipality",
        "extraction_confidence": 0.9,
        "notes": "2,400-tonne/day waste-to-energy plant, largest in MENA",
    },
    # Infrastructure / Social
    {
        "name": "Yas Island Infrastructure Master Development",
        "sector": "Infrastructure",
        "emirate": "Abu Dhabi",
        "owner": "Miral Asset Management",
        "contract_value_aed": 30.0,
        "status": "Under Execution",
        "contractors": "Multiple contractors",
        "expected_completion_year": 2030,
        "source_url": "https://www.miral.ae",
        "source_name": "Miral",
        "extraction_confidence": 0.85,
        "notes": "Tourism and entertainment mega-development",
    },
    {
        "name": "Dubai Creek Harbour Infrastructure",
        "sector": "Infrastructure",
        "emirate": "Dubai",
        "owner": "Emaar Properties / Dubai Holding",
        "contract_value_aed": 22.0,
        "status": "Under Execution",
        "contractors": "Arabtec, Samsung C&T",
        "expected_completion_year": 2027,
        "source_url": "https://www.dubaicrrekharbour.ae",
        "source_name": "Emaar Properties",
        "extraction_confidence": 0.85,
        "notes": "Mixed-use waterfront development including Dubai Creek Tower",
    },
    {
        "name": "Zayed City Infrastructure (Khalifa City B)",
        "sector": "Infrastructure",
        "emirate": "Abu Dhabi",
        "owner": "Abu Dhabi City Municipality",
        "contract_value_aed": 8.0,
        "status": "Under Execution",
        "contractors": "Al Habtoor Group, Samsung",
        "expected_completion_year": 2026,
        "source_url": "https://www.abudhabi.ae",
        "source_name": "Abu Dhabi Municipality",
        "extraction_confidence": 0.8,
        "notes": "New urban district with utilities, roads and social infrastructure",
    },
    {
        "name": "ADIO Industrial Cities PPP (KEZAD)",
        "sector": "Infrastructure",
        "emirate": "Abu Dhabi",
        "owner": "Abu Dhabi Ports / ADIO",
        "contract_value_aed": 12.0,
        "status": "Under Execution",
        "contractors": "Multiple industrial partners",
        "expected_completion_year": 2030,
        "source_url": "https://www.adio.gov.ae",
        "source_name": "ADIO",
        "extraction_confidence": 0.85,
        "notes": "Khalifa Economic Zones — manufacturing and logistics PPP clusters",
    },
    {
        "name": "Umm Al Quwain Smart Utilities PPP",
        "sector": "Infrastructure",
        "emirate": "Umm Al Quwain",
        "owner": "Umm Al Quwain Municipality",
        "contract_value_aed": 0.8,
        "status": "Tendering",
        "contractors": None,
        "expected_completion_year": 2026,
        "source_url": "https://www.uaq.ae",
        "source_name": "UAQ Municipality",
        "extraction_confidence": 0.75,
        "notes": "Smart metering and utilities management PPP",
    },
    {
        "name": "Federal Roads Network PPP",
        "sector": "Transport",
        "emirate": "Federal",
        "owner": "Ministry of Energy and Infrastructure",
        "contract_value_aed": 15.0,
        "status": "Planned",
        "contractors": None,
        "expected_completion_year": 2030,
        "source_url": "https://www.moei.gov.ae",
        "source_name": "MOEI",
        "extraction_confidence": 0.8,
        "notes": "Inter-emirate road network upgrades and maintenance PPP",
    },
    {
        "name": "Dubai Affordable Housing PPP Programme",
        "sector": "Social",
        "emirate": "Dubai",
        "owner": "Dubai Real Estate Corporation (DREC)",
        "contract_value_aed": 5.0,
        "status": "Tendering",
        "contractors": None,
        "expected_completion_year": 2028,
        "source_url": "https://www.dof.gov.ae",
        "source_name": "Dubai DOF",
        "extraction_confidence": 0.8,
        "notes": "Government-private partnership for affordable residential units",
    },
    {
        "name": "Abu Dhabi Social Infrastructure PPP",
        "sector": "Social",
        "emirate": "Abu Dhabi",
        "owner": "Department of Community Development Abu Dhabi",
        "contract_value_aed": 3.2,
        "status": "Under Execution",
        "contractors": "ALEC, Bloom Properties",
        "expected_completion_year": 2026,
        "source_url": "https://www.dcd.gov.ae",
        "source_name": "DCD Abu Dhabi",
        "extraction_confidence": 0.8,
        "notes": "Community centres, youth facilities and senior care PPP",
    },
    {
        "name": "Sharjah Social Infrastructure Development",
        "sector": "Social",
        "emirate": "Sharjah",
        "owner": "Sharjah Social Services Department",
        "contract_value_aed": 1.5,
        "status": "Under Execution",
        "contractors": "Sharjah Holding",
        "expected_completion_year": 2025,
        "source_url": "https://www.sharjah.gov.ae",
        "source_name": "Sharjah Government",
        "extraction_confidence": 0.75,
        "notes": "Community services and welfare facilities",
    },
    {
        "name": "Dubai DOF PPP Pilot Projects",
        "sector": "Infrastructure",
        "emirate": "Dubai",
        "owner": "Dubai Department of Finance (DOF)",
        "contract_value_aed": 6.0,
        "status": "Planned",
        "contractors": None,
        "expected_completion_year": 2028,
        "source_url": "https://www.dof.gov.ae/ppp",
        "source_name": "Dubai DOF PPP",
        "extraction_confidence": 0.8,
        "notes": "First wave of PPP projects under Dubai PPP Law No. 22 of 2015",
    },
]


async def seed() -> None:
    await init_db()
    async with AsyncSessionLocal() as session:
        created_count = 0
        skipped_count = 0
        for project_data in SEED_PROJECTS:
            _, created = await upsert_project(session, project_data)
            if created:
                created_count += 1
            else:
                skipped_count += 1
        await session.commit()
    print(f"Seeding complete: {created_count} created, {skipped_count} skipped. Total: {len(SEED_PROJECTS)} projects.")


if __name__ == "__main__":
    asyncio.run(seed())
